### ISSUE TITLE
Nueva entidad MetodoDePago

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/2024_gc_p2_g5_sf#5]
Crear una nueva entidad `MetodosDePago` en el paquete `entity` con los siguientes atributos:

* id
* tipoMetodo
* detallesMetodoPago
* activo

**Requisitos:**

* Eliminar constructores no utilizados y anotaciones redundantes.
* Incluir una captura de pantalla de la tabla `MetodosDePago` generada en la base de datos en el pull request.

**Comment by ahumadamob** [comment]
Habría que retirar entonces el archivo de envíos, sin eliminarlo del proyecto. De la siguiente manera:

1. **Crea una nueva rama de respaldo** (por si acaso):
   ```bash
   git checkout -b backup-branch
   ```

2. **Vuelve a la rama original donde hiciste el commit y el push**:
   ```bash
   git checkout <nombre-de-la-rama-original>
   ```

3. **Deshaz el último commit pero mantén los cambios en el área de trabajo**:
   ```bash
   git reset --soft HEAD~1
   ```

4. **Quita los archivos que no quieres que estén en el commit del área de preparación (staging)**:
   ```bash
   git reset HEAD <archivo-que-no-debía-incluirse>
   ```

   Repite este paso para cada archivo que quieras excluir del commit. Si son muchos archivos, puedes usar patrones o listas para seleccionarlos todos de una vez.

5. **Vuelve a hacer el commit solo con los archivos que quieres incluir**:
   ```bash
   git commit -m "Mensaje del commit solo con el archivo deseado"
   ```

6. **Haz el push del nuevo commit forzando el historial de la rama en el repositorio remoto**:
   ```bash
   git push origin <nombre-de-la-rama> --force
   ```

7. **(Opcional) Crea un nuevo commit con los archivos excluidos si necesitas guardarlos**:
   Si los archivos que has excluido del commit deben mantenerse en el repositorio pero no formaban parte del commit inicial por error, puedes hacer un nuevo commit con ellos:
   ```bash
   git add <archivo-que-quieres-incluir>
   git commit -m "Commit de respaldo de los archivos excluidos"
   git push origin <nombre-de-la-rama>
   ```

**Comment by PHFM80** [comment]
profe ahi trate de eliminar los dos commits, y me parece que lo logre, pero cuando trate de hacer un nuevo commit con el archivo metodos de pago me da un error en git.  el miercoles llevo la maquina y le muestro

**Comment by PHFM80** [comment]
Profe, buenas noches.  Creo que pude resolver el conflicto que se estaba generando, ya realice el push.  espero su revision
