### ISSUE TITLE
Persistencia avanzada de Inventario

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/2024_gc_p2_g5_sf#55]
#### Descripción:

Desarrollar un controlador en Spring Boot para gestionar la entidad **Inventario** con las siguientes operaciones:

1. **Obtener todos los productos en inventario**:
   - Implementar un método que permita obtener una lista de todos los productos en inventario.
   - Si no se encuentran productos, devolver un mensaje indicando que no hay datos disponibles.

2. **Buscar producto en inventario por ID**:
   - Implementar un método que permita buscar un producto específico en inventario por su ID.
   - Si el producto no se encuentra, devolver un mensaje indicando que el producto no existe.

3. **Agregar un nuevo producto al inventario**:
   - Implementar un método para agregar un nuevo producto al inventario.
   - Si el producto ya existe (según su ID), devolver un mensaje de error indicando duplicación.

4. **Actualizar un producto existente en el inventario**:
   - Implementar un método que permita actualizar los datos de un producto en el inventario.
   - Si el producto no existe, devolver un mensaje indicando que no se puede actualizar un producto inexistente.

5. **Eliminar un producto del inventario**:
   - Implementar un método que permita eliminar un producto del inventario por su ID.
   - Si el producto no existe, devolver un mensaje indicando que no se pudo encontrar el producto para eliminar.

6. **Verificar la existencia de un producto en inventario**:
   - Crear un método llamado `exists` que verifique si un producto existe en el inventario según su ID.

#### Requisitos:

- Utilizar un **DTO (Data Transfer Object)** con los siguientes atributos:
   - `estado`: Indica si la operación fue exitosa o fallida.
   - `mensaje`: Contiene un mensaje de error o éxito.
   - `producto`: El producto consultado o modificado.

- **Nota**: Se permite usar **ResponseEntity**, pero no es obligatorio.

#### Documentación:

- Incluir comentarios en el código que expliquen los siguientes conceptos:
   - **Encapsulamiento**: Ejemplos de getters y setters dentro de una clase.
   - **Instancia de objeto**: Creación de un nuevo objeto de tipo Producto en alguna parte del controlador o servicio.
   - **Inicialización de objetos**: Ejemplo de inicialización de un objeto Producto.

#### Pruebas:

Como parte de la entrega, adjuntar capturas de pantalla correspondientes a las pruebas realizadas con **Postman** para las siguientes situaciones:
- Búsqueda exitosa de todos los productos en inventario.
- Búsqueda de producto en inventario por ID exitosa.
- Búsqueda fallida por un ID inexistente.
- Agregar un nuevo producto al inventario.
- Intento de agregar un producto con ID ya existente.
- Actualización exitosa de un producto en el inventario.
- Intento de actualizar un producto inexistente.
- Eliminación exitosa de un producto del inventario.
- Intento de eliminar un producto inexistente.
- Verificación de existencia de un producto en inventario.

**Comment by rocbrr** [comment]
***- Búsqueda exitosa de todos los productos en inventario:***
![imagen](https://github.com/user-attachments/assets/8ed65cf9-4672-4b70-a3b0-8de0f36fe53f)
***- Búsqueda de producto en inventario por ID exitosa:***
![imagen](https://github.com/user-attachments/assets/46d2fbea-f0a5-47c7-a33b-94e9ee20caf5)
***- Búsqueda fallida por un ID inexistente:***
![imagen](https://github.com/user-attachments/assets/f76407fd-b6b0-47fd-9eb9-bea287ca5c67)
***- Agregar un nuevo producto al inventario:***
![imagen](https://github.com/user-attachments/assets/6be42aa9-2950-4787-89c0-bc08d9768605)
***- Intento de agregar un producto con ID ya existente:***
![imagen](https://github.com/user-attachments/assets/4274a990-11bd-4810-a5de-3ff24d4cd941)
***- Actualización exitosa de un producto en el inventario:***
![imagen](https://github.com/user-attachments/assets/7520c04b-a7a1-4832-a116-1210cf6f244b)
***- Intento de actualizar un producto inexistente:***
![imagen](https://github.com/user-attachments/assets/4d97dd56-9bf6-4adc-8428-8615b043eba1)
***- Eliminación exitosa de un producto del inventario:***
![imagen](https://github.com/user-attachments/assets/5648bfbc-4a10-487b-bc20-f9fe2b2aa4e5)
***- Intento de eliminar un producto inexistente:***
![imagen](https://github.com/user-attachments/assets/34b7ab29-de24-4dcc-8c65-fb87d796f1b3)
***- Verificación de existencia de un producto en inventario:***
![imagen](https://github.com/user-attachments/assets/d91b3183-164d-4d01-8a3a-8f902e363fa7)
