### ISSUE TITLE
Persistencia avanzada de MetodoDePago

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/2024_gc_p2_g5_sf#58]
#### Descripción:

Desarrollar un controlador en Spring Boot para gestionar la entidad **MetodoDePago** con las siguientes operaciones:

1. **Obtener todos los métodos de pago**:
   - Implementar un método que permita obtener una lista de todos los métodos de pago disponibles.
   - Si no se encuentran métodos de pago, devolver un mensaje indicando que no hay datos disponibles.

2. **Buscar método de pago por ID**:
   - Implementar un método que permita buscar un método de pago específico por su ID.
   - Si el método de pago no se encuentra, devolver un mensaje indicando que el método de pago no existe.

3. **Agregar un nuevo método de pago**:
   - Implementar un método para agregar un nuevo método de pago.
   - Si el método de pago ya existe (según su ID), devolver un mensaje de error indicando duplicación.

4. **Actualizar un método de pago existente**:
   - Implementar un método que permita actualizar los datos de un método de pago.
   - Si el método de pago no existe, devolver un mensaje indicando que no se puede actualizar un método de pago inexistente.

5. **Eliminar un método de pago**:
   - Implementar un método que permita eliminar un método de pago por su ID.
   - Si el método de pago no existe, devolver un mensaje indicando que no se pudo encontrar el método de pago para eliminar.

6. **Verificar la existencia de un método de pago**:
   - Crear un método llamado `exists` que verifique si un método de pago existe en la base de datos según su ID.

#### Requisitos:

- Utilizar un **DTO (Data Transfer Object)** con los siguientes atributos:
   - `estado`: Indica si la operación fue exitosa o fallida.
   - `mensaje`: Contiene un mensaje de error o éxito.
   - `metodoDePago`: El método de pago consultado o modificado.

- **Nota**: Se permite usar **ResponseEntity**, pero no es obligatorio.

#### Documentación:

- Incluir comentarios en el código que expliquen los siguientes conceptos:
   - **Encapsulamiento**: Ejemplos de getters y setters dentro de una clase.
   - **Instancia de objeto**: Creación de un nuevo objeto de tipo MetodoDePago en alguna parte del controlador o servicio.
   - **Inicialización de objetos**: Ejemplo de inicialización de un objeto MetodoDePago.

#### Pruebas:

Como parte de la entrega, adjuntar capturas de pantalla correspondientes a las pruebas realizadas con **Postman** para las siguientes situaciones:
- Búsqueda exitosa de todos los métodos de pago.
- Búsqueda de método de pago por ID exitosa.
- Búsqueda fallida por un ID inexistente.
- Agregar un nuevo método de pago.
- Intento de agregar un método de pago con ID ya existente.
- Actualización exitosa de un método de pago.
- Intento de actualizar un método de pago inexistente.
- Eliminación exitosa de un método de pago.
- Intento de eliminar un método de pago inexistente.
- Verificación de existencia de un método de pago.

**Comment by Sofiaravena** [comment]
Búsqueda exitosa de todos los métodos de pago.
![Captura de pantalla (121)](https://github.com/user-attachments/assets/352609ea-55e4-4a26-ae1d-aa95e5e9dac1)
Búsqueda de método de pago por ID exitosa.
![Captura de pantalla (122)](https://github.com/user-attachments/assets/a6fb5e5e-960a-44fa-add7-c458bb1dea04)
Búsqueda fallida por una identificación inexistente.
![Captura de pantalla (123)](https://github.com/user-attachments/assets/228f5a2e-54a3-4969-96a5-b9956af1d681)
Agregando un nuevo método de pago.
![Captura de pantalla (124)](https://github.com/user-attachments/assets/4d02c8d8-e6ce-408a-8c51-68b37e62ac9c)
Intento de agregar un método de pago con ID ya existente.
![Captura de pantalla (125)](https://github.com/user-attachments/assets/64abe058-1fae-4f16-a8f7-8c83a42a8529)
Actualización exitosa de un método de pago.
![Captura de pantalla (126)](https://github.com/user-attachments/assets/c421d869-6875-49a1-aec4-be22fee6913e)
Intento de actualizar un método de pago inexistente.
![Captura de pantalla (127)](https://github.com/user-attachments/assets/50c6bbd7-cd50-4225-b8da-e3097a77947f)
Eliminación exitosa de un método de pago.
![Captura de pantalla (128)](https://github.com/user-attachments/assets/836e15d0-eb7a-4276-805d-df449896181e)
Intento de eliminar un método de pago inexistente.
![Captura de pantalla (129)](https://github.com/user-attachments/assets/23b9d304-11e8-4e02-812b-40379caa0830)
Verificación de existencia de un método de pago.
![Captura de pantalla (130)](https://github.com/user-attachments/assets/c519b778-241d-4fe0-b986-8045a68ebcdf)
